"""add_execution_timeout_to_jobs

Revision ID: ecb29f1a7145
Revises: a1b2c3d4e5f6
Create Date: 2026-07-03 17:47:02.254389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb29f1a7145'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with a server_default so existing rows are populated before NOT NULL is enforced
    op.add_column('jobs', sa.Column('execution_timeout', sa.Integer(), nullable=False, server_default='3600'))
    op.add_column('queues', sa.Column('default_execution_timeout', sa.Integer(), nullable=False, server_default='3600'))
    # Remove server_default after backfill so future rows use the app-level default
    op.alter_column('jobs', 'execution_timeout', server_default=None)
    op.alter_column('queues', 'default_execution_timeout', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'default_execution_timeout')
    op.drop_column('jobs', 'execution_timeout')
    # ### end Alembic commands ###
